config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'synestesie', to: 'pages#synestesie'
  get 'about', to: 'pages#about'
  get 'start', to: 'pages#start'
  get 'contact', to: 'pages#contact'
  get 'legal', to: 'pages#legal'

  root to: 'pages#home'

  resources :answers do #drummers
    resources :questions, only: [:new, :create, :index, :destroy, :show]
  end
    resources :questions

  get '/play', to: 'games#play'
  get '/welcome', to: 'games#welcome'
  post '/check', to: 'games#check'
  get '/loose', to: 'games#loose'
  get '/congrat', to: 'games#congrat'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :picture, presence: true
  has_many :questions, dependent: :destroy
  mount_uploader :picture, PictureUploader
end

app/models/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for (flash_type)
    case flash_type
      when :alert then "alert-error"
      when :notice then "alert-success"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :answer
  validates :picture, presence: true
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [ :edit, :update, :destroy ]

  def index
    @answers = Answer.all.order(name: :asc)
  end
  def new
    @answer = Answer.new
  end
  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:notice] = "Answer #{@answer.name} has been successfully created"
      redirect_to edit_answer_path(@answer)
    else
      flash[:alert] = "Error : Answer not created"
      render :new
    end
  end
  def edit
    @question = Question.new
    @questions = @answer.questions
  end
  def update
    @answer.update(answer_params)
    flash[:notice] = "Answer #{@answer.name} has been successfully updated"
    redirect_to answers_path
  end
  def destroy
    @answer.destroy
    flash[:notice] = "Answer #{@answer.name} has been successfully deleted"
    redirect_to answer_path
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end
  def answer_params
    params.require(:answer).permit(:name, :picture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
attr_accessor :lvl

  def welcome
  end

  def congrat
  end

  def play
    lvlup(lvl)
    if lvl == 1
      set_questions
    else
      get_questions
    end
    @answers = Answer.where.not(id: question.answer_id).limit(2).order("RANDOM()").to_a
    @answer ||= []
    @answers << question.answer
    @answers = @answers.shuffle
    render 'play'
  end

  def loose
      @question = Question.find(params[:question])
      flash.now[:alert] = "Miss..."
      render 'loose'
  end

  def check
    @lvl = params[:lvl].to_i
    answer_id = params[:id].to_i
    question = Question.find(params[:question])
    if @lvl == lvlmax
      render action: 'congrat' and return
    elsif answer_id == question.answer_id
      flash.now[:notice] = "Well done !"
      play
    else answer_id != question.answer_id
      loose
    end
  end

  private

  def lvlup(value)
    @lvl = 1 + value.to_i
  end
  def lvlmax
    @lvlmax = Question.all.count
  end

  def set_questions
    @questionsids = []
    Question.all.shuffle.each do |d|
      @questionsids << d.id
    end
    cookies[:questions] = @questionsids
  end

  def get_questions
    @questions = cookies[:questions].split('&')
  end

  def questions
    @questions = cookies[:questions]
  end

  def question
    @question = Question.find(questions[lvl])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def synestesie
  end

  def start
  end

  def contact
  end

  def legal
  end

  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_answer, only: :create

  def create
    @question = @answer.questions.new(question_params)
    @question.save
    flash[:notice] = "Question successfully assigned to  #{@answer.name}"
    redirect_to edit_answer_path(@answer)
  end
  def destroy
    question = Question.find(params[:id])
    question.destroy
    flash[:notice] = "Question successfully deleted"
    redirect_to edit_answer_path(question.answer)
  end

  private

  def question_params
    params.require(:question).permit(:answer_id, :picture)
  end
  def find_answer
    @answer = Answer.find(params[:answer_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/_answer_form.html.erb
<%= simple_form_for @answer  do |f| %>
  <%= f.input :name %>
  <%= f.input :picture, label: icon('picture-o')+" Picture", label_html: { class: 'btn btn-primary' } %>
  <%= f.button :submit, class: "btn btn-success"%>
<% end %>

app/views/answers/edit.html.erb
<%= link_to icon('reply') + " Back", { controller: "answers" , action: "index"}, class: "btn btn-primary"  %>
<h1 class="text-center">Edit  <%= @answer.name %></h1>
<div class="row">
  <div class="col-lg-6 col-md-12 col-sm-12 form-group">
    <%= cl_image_tag(@answer.picture, :width => 200, :height => 200, :crop => :thumb, :gravity => :face, :radius => :max, class: "img-circle") %>
    <%= render 'answer_form' %>

    <h3>Assignate a new question</h3>
    <%= simple_form_for [ @answer, @question ] do |f| %>
    <%= f.input :picture, label: icon('picture-o')+" Picture", label_html: { class: 'btn btn-primary' } %>
    <%= f.button :submit , class: "btn-info btn-block" %>
    <% end %>
  </div>
  <div class="col-lg-6 col-md-12 col-sm-12 form-group">
    <% @questions.each do |question|  %>
      <div class="form-group">
        <%= cl_image_tag(question.picture, class: "img-responsive img-thumbnail") %>
        <%= link_to icon('trash') + " Remove question", question_path(question) , method: :delete , class: "btn btn-danger btn-block" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 form-group">
    <%= link_to icon('trash') + " Remove "+@answer.name, answer_path(@answer.id) , method: :delete , class: "btn btn-danger btn-block" %>
  </div>
</div>

app/views/answers/index.html.erb
<h1 class="center">Answers list</h1>

<div class="row form-group">
  <%= link_to icon('plus') + " Add answer", new_answer_path, class: "btn btn-primary btn-block" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Nn Questions</th>
      <th>Questions</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= cl_image_tag(answer.picture, :width => 70, :height => 70,
          :crop => :thumb, :gravity => :face, :radius => :max, class: "img-circle") %></td>
        <td><h3 class="btn btn-primary"><%= link_to answer.name , edit_answer_path(answer) %></h3></td>
        <td><%= answer.questions.count %></td>
        <td>
            <% answer.questions.each do |question| %>
            <%= cl_image_tag(question.picture, :width => 80, :height => 80, class: "img-rounded") %>
              <% end %>
        </td>
        <td><%= link_to icon('trash'), answer_path(answer),
        method: :delete,
        data: { confirm: "Are you sure?" },
        class: "btn btn-primary btn-block" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/answers/new.html.erb
<h1 class="text-center">Add a answer</h1>
<%= render 'answer_form' %>

app/views/answers/show.html.erb
<h1 class="text-center"><%= @answer.name %></h1>
<%= cl_image_tag(@answer.picture,:width => 150, :height => 150,
             :crop => :thumb, :gravity => :face, :radius => :max )%>

<%= link_to "Edit", edit_answer_path(@answer.id), class: "btn btn-info btn-block"%>

app/views/games/check.html.erb
<h1>Games#check</h1>
<p>Find me in app/views/games/check.html.erb</p>

app/views/games/congrat.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="display-3 text-xs-center mt animated bounceInDown">Congratulation !</h1>
  </div>
</div>
<div class="row">
  <h4 class="center">You have reached the level max, we have no more questions in stock...<br>
    But you can still propose your favorite answer <%= link_to "here", '/welcome', class: "animated flash text-primary" %>
  </h4>

  <div class="center">
    <%= link_to icon('reply') + " Play again", '/play', class: "btn btn-secondary animated pulse infinite" %>
  </div>
</div>

app/views/games/loose.html.erb
<h1 class="text-xs-center">Game Over</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 lvl">
    <progress class="progress progress-danger animated flash" value="<%= @lvl %>" max="30"><%= @lvl %>%</progress>
  </div>
</div>

<h4 class="center"><span class="label label-pill label-danger center animated flash">Level : <%= @lvl %></span></h4>
<div class="row">
  <div class="col-md-12">
    <%= cl_image_tag(@question.picture, width: 500, id: "img-loose", class: "img-thumbnail img-fluid center-block animated hinge") %>
  </div>
</div>

<h4 class="center">Good answer : </h4>

<p class="center">
  <a  target="_blank" href="https://www.google.com/#q=<%= @question.answer.name %>" tabindex="0" class="btn" role="button" data-trigger="manual" data-toggle="popover" title="Asshole !" data-content="Click on my face to learn who I am.">
  <%= cl_image_tag(@question.answer.picture, :width => 70, :height => 70,
    :crop => :thumb, :gravity => :face, :radius => :max, :effect => "saturation:-100", class: "img-circle center animated fadeIn") %>
  </a>
</p>

<h3 class="center">
  <%= @question.answer.name %>
</h3>

<div class="center">
  <%= link_to icon('reply') + " Retry", '/play', class: "btn btn-danger animated flash" %>
</div>

app/views/games/play.html.erb
<h3 class="text-xs-center">What is the right answer ?</h3>

<h4 class="text-xs-center"><span class="label label-pill label-primary center animated flash">Level : <%= @lvl %></span></h4>

<div class="row form-group">
  <div class="col-md-12">
    <%= cl_image_tag(@question.picture, width: 500, class: "img-thumbnail img-fluid center-block animated fadeIn") %>
  </div>
</div>

<div class="row center" data-toggle="buttons">
  <div class="col-xs-12">
    <%= form_tag('/check') %>
      <%= hidden_field_tag 'lvl', @lvl %>
      <%= hidden_field_tag 'question', @question.id %>

      <div class="btn-group" data-toggle="buttons">
        <% @answers.each do |answer| %>

          <label class="btn btn-secondary btn-drummer">
            <%= cl_image_tag(answer.picture, :width => 70, :height => 70,
                  :crop => :thumb, :gravity => :face, :radius => :max, :effect => "saturation:-100", class: "img-circle img-fluid center-block animated fadeIn") %>
            <%= radio_button_tag 'id', answer.id %>
            <p class="small"><%= answer.name %></p>
          </label>
        <% end %>
      </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 lvl">
    <progress class="progress animated flipInX" value="<%= @lvl %>" max="30"><%= @lvl %>%</progress>
  </div>
</div>

app/views/games/welcome.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="display-3 text-xs-center mt animated bounceInDown text-center">Are you <%= icon('heart', class: "text-danger animated pulse infinite") %> ready ?</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3 center animated bounceInUp">
    <%= link_to icon('gamepad') + " Test your knowledge", "/play", class: "btn btn-primary btn-lg mt"  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SNSTS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="container">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>

  <script>
  var ready = function() {
  $('label').on('change', function() {
    $('form').submit();
  });

  $(function () {
    $('[data-toggle="popover"]').popover('show')
  });

};

$(document).ready(ready);
$(document).on('page:load', ready);

  </script>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/legal.html.erb
<h1>Pages#legal</h1>
<p>Find me in app/views/pages/legal.html.erb</p>

app/views/pages/start.html.erb
<h1>Pages#start</h1>
<p>Find me in app/views/pages/start.html.erb</p>

app/views/pages/synestesie.html.erb
<h1>Pages#synestesie</h1>
<p>Find me in app/views/pages/synestesie.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit</h1>

<div class="row">
  <div class="col-lg-6 col-md-12 col-sm-12 form-group">
    <%= simple_form_for @question, :html => {:multipart => true} do |f| %>
      <%= cl_image_tag(@question.picture) %>
      <%= f.input :picture %>
      <%= f.input :drummer_id %>

      <%= f.button :submit , class: "btn-warning btn-block" %>
    <% end %>
  </div>


<div class="row">
  <div class="col-lg-6 col-md-12 col-sm-12 form-group">
    <%= link_to "Remove", question_path(@question.id) , method: :delete , class: "btn btn-danger btn-block" %>
  </div>
</div>

app/views/questions/index.html.erb
<h1 class="text-center">Questions list</h1>

<div class="row">
  <% @questions.each do |question| %>
    <%= cl_image_tag(question.picture, :width => 80, :height => 80, class: "img-rounded") %>
    <%= link_to "Remove", question_path(question) , method: :delete , class: "btn btn-danger btn-block" %>
  <% end %>
</div>
<div class="row">
  <%= link_to new_answer_question_path(@answer)  %>
</div>

app/views/questions/new.html.erb
<%= simple_form_for [@answer, @question], :html => {:multipart => true} do |f| %>
  <%= f.input :picture %>
  <%= f.association :answer %>
  <%= f.button :submit , class: "btn-info btn-block" %>
<% end %>

app/views/questions/show.html.erb
<%= cl_image_tag(@question.picture) %>
    <%= @answer.name %>

app/views/shared/_flash.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">

    <% if flash[:notice] %>
      <div class="alert alert-success animated fadeInDown">
        <button class="close" data-dismiss="alert">×</button>
        <%= icon('angellist') + " " +flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="alert alert-danger animated bounceInDown">
      <button class="close" data-dismiss="alert">×</button>
      <%= icon('thumbs-o-down') + " " +flash[:alert] %>
    </div>
    <% end %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "synestasia-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>